apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ctse-product-service
  name: ctse-product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctse-product-service
  template:
    metadata:
      labels:
        app: ctse-product-service
    spec:
      containers:
      - name: product-service
        image: it18217100/product-service
        imagePullPolicy: Always
        ports:
        - containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: ctse-product-service
spec:
  ports:
  - targetPort: 9001
    port: 9001
  selector:
    app: ctse-product-service